version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: "no"
    ports:
       - 5672:5672
       - 15672:15672
  features:
    build:
      context: ./features
    restart: "no"
    depends_on:
      - rabbitmq
  model:
    build:
      context: ./model
    restart: "no"
    depends_on:
      - features
  metric:
    build:
      context: ./metric
    restart: "no"
    depends_on:
      - model
  plot:
    build:
      context: ./plot
    volumes:
      - ./logs:/logs
    restart: "no"
    depends_on:
      - metric
    
